### ISSUE TITLE
Error 1050: Table 'migration_version' already exists

### ISSUE THREAD

**Issue by ianwalter** [drone/drone#1059]
I'm running Drone in a Docker container and I've got it linked to a MySQL container. If I try to re-run the image, I get the following error and the container stops:

```
2015-06-13T19:49:44.903647213Z panic: Could not get DB version: Error 1050: Table 'migration_version' already exists
2015-06-13T19:49:44.903647213Z 
2015-06-13T19:49:44.903647213Z goroutine 16 [running]:
2015-06-13T19:49:44.903647213Z runtime.panic(0xaac3c0, 0xc208170440)
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
2015-06-13T19:49:44.903647213Z github.com/drone/drone/server/datastore/database.MustConnect(0xc208135fd8, 0x5, 0xc208161520, 0x1e, 0x0)
2015-06-13T19:49:44.903647213Z 	/var/cache/drone/src/github.com/drone/drone/server/datastore/database/database.go:52 +0x8a
2015-06-13T19:49:44.903647213Z main.main()
2015-06-13T19:49:44.903647213Z 	/var/cache/drone/src/github.com/drone/drone/server/main.go:104 +0x274
2015-06-13T19:49:44.903647213Z 
2015-06-13T19:49:44.903647213Z goroutine 19 [finalizer wait]:
2015-06-13T19:49:44.903647213Z runtime.park(0x4a8630, 0x11bcf58, 0x11a79a9)
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
2015-06-13T19:49:44.903647213Z runtime.parkunlock(0x11bcf58, 0x11a79a9)
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
2015-06-13T19:49:44.903647213Z runfinq()
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
2015-06-13T19:49:44.903647213Z runtime.goexit()
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/runtime/proc.c:1445
2015-06-13T19:49:44.903647213Z 
2015-06-13T19:49:44.903647213Z goroutine 22 [syscall]:
2015-06-13T19:49:44.903647213Z os/signal.loop()
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
2015-06-13T19:49:44.903647213Z created by os/signal.init·1
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32
2015-06-13T19:49:44.903647213Z 
2015-06-13T19:49:44.903647213Z goroutine 24 [chan receive]:
2015-06-13T19:49:44.903647213Z database/sql.(*DB).connectionOpener(0xc208050600)
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/database/sql/sql.go:583 +0x48
2015-06-13T19:49:44.903647213Z created by database/sql.Open
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/database/sql/sql.go:442 +0x27c
2015-06-13T19:49:44.903647213Z 
2015-06-13T19:49:44.903647213Z goroutine 17 [syscall]:
2015-06-13T19:49:44.903647213Z runtime.goexit()
2015-06-13T19:49:44.903647213Z 	/usr/local/go/src/pkg/runtime/proc.c:1445
```

This might be more of an issue with the migration library not being able to handle this case, but it's the last issue I'm having with what is otherwise an awesome CI setup. Thank you.

**Comment by bradrydzewski** [comment]
@ianwalter the migration library will attempt to run the following query: `SELECT version FROM migration_version`. If that query fails or returns zero results it will attempt to create the migration table. If the migration table exists there should always be at least one entry (with migration number 0) in the table.

You can see the logic here:
https://github.com/drone/drone/blob/master/server/datastore/migrate/version.go#L10

I'm wondering what would cause this query to fail. Did you do any manual database manipulation at some point? For example, deleting rows from the migration table in an attempt to start fresh?

**Comment by ianwalter** [comment]
I haven't done any manual database manipulation other than dropping the entire database and recreating it so that I could get Drone to work again (after running into this issue). Could it be that this issue is coming from setVersion instead of getVersion? Maybe the error is from trying to run the update query?

**Comment by bradrydzewski** [comment]
What is the state of the database? can you see any of the other tables (ie repos, users, etc)? Does the migration table exist? If yes, what version number was inserted?

Unfortunately I'm unable to repeat the issue, so we'll need to troubleshoot from your machine

**Comment by ianwalter** [comment]
```
mysql> show tables;                                                             
+-------------------+                                                           
| Tables_in_drone   |                                                           
+-------------------+                                                           
| blobs             |                                                           
| commits           |                                                           
| migration_version |                                                           
| perms             |                                                           
| repos             |                                                           
| users             |                                                           
+-------------------+                                                           
```

```
mysql> select * from migration_version;                                         
+---------+                                                                     
| version |                                                                     
+---------+                                                                     
|       3 |                                                                     
+---------+
```

I'll try to reproduce in a local environment so that I can debug it. Thanks.

**Comment by bradrydzewski** [comment]
Thanks, I really appreciate you digging deeper into this. Let me know if you can reproduce locally

**Comment by bradrydzewski** [comment]
closing since I haven't heard anything. I also switched migration engine from `burntshshi/migration` to `rubenv/sql-migrate` which hopefully resolves any lingering issues as well. If we find an issue with `sql-migrate` we can re-open
