### ISSUE TITLE
0.4 don't work build 

### ISSUE THREAD

**Issue by antonikonovalov** [drone/drone#1136]
remote - gitlab
run like 
```
git pull origin 0.4-database && make all
sudo DOCKER_HOST="unix:///var/run/docker.sock" SERVER_ADDR=":8084" REMOTE_DRIVER="gitlab" REMOTE_CONFIG="http://gitlab.local/?client_id={client}&client_secret={sec}" ./bin/drone

```

.drone.yml
```build:
  image: golang
  commands:
    - go get
    - go build
    - go test
```
error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x404241]

goroutine 16 [running]:
runtime.panic(0x706920, 0x8f7f73)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.createClone(0xc20804c200, 0x0, 0x0)
	/home/brad/gocode/src/github.com/drone/drone/cmd/drone-build/main.go:119 +0x411
main.main()
	/home/brad/gocode/src/github.com/drone/drone/cmd/drone-build/main.go:40 +0x18a

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
	/usr/local/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
	/usr/local/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445
```
![image](https://cloud.githubusercontent.com/assets/1614346/9268815/6a5c2b56-426b-11e5-90cb-9b2dd2d5a462.png)

**Comment by bradrydzewski** [comment]
hey there, thanks for testing out the 0.4 branch! It is very unstable and many things still don't work. This particular feature, however, works for me and I'm unable to reproduce. Are you willing to trace through the code a bit more to help pinpoint the issue?

**Comment by bradrydzewski** [comment]
EDIT: let me run some more tests.  The drone plugin model can make things a bit more difficult now, because we can be using two different docker containers. Let me make sure the build agent container I have locally matches the one published to docker hub

I'll post back when I've done more testing

**Comment by antonikonovalov** [comment]
ok, I am try get more info

**Comment by antonikonovalov** [comment]
maybe I need to run something else more?
now i do it nest  steps 
```
$ git clone && git co 0.4-database
$ sudo  docker build --file=Dockerfile.alpine --rm=true -t drone/drone-alpine .
$ sudo docker run \
        --volume /var/lib/drone:/var/lib/drone \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --env-file drone.env \
        --restart=always \
        --net=bridge \
        --dns=x.x.x.x \
        --publish=8084:8084 \
        -a STDOUT drone/drone-alpine
```
it's worked but result equals

**Comment by antonikonovalov** [comment]
after mergin #1135 - it's work!
