### ISSUE TITLE
Panic when receiving some github hooks

### ISSUE THREAD

**Issue by hkjn** [drone/drone#1168]
Found running drone build from `master@7347be7c762`.

I noticed that some github hooks weren't coming through, associated with panics like the following in `docker logs drone`. Other (most) hooks are working fine, and I'm not sure what the difference is:
```
2015/08/26 13:00:13 http: panic serving 192.30.252.34:48839: runtime error: invalid memory address or nil pointer dereference
goroutine 122975 [running]:
net/http.func·011()
        /usr/src/go/src/net/http/server.go:1130 +0xbb
github.com/drone/drone/server/handler.PostHook(0xc208bd35c0, 0xc208bd33e0, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/drone/drone/server/handler/hook.go:46 +0x1283
github.com/zenazn/goji/web.handlerFuncWrap.ServeHTTPC(0xd82cc0, 0xc208bd35c0, 0xc208bd33e0, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/zenazn/goji/web/handler.go:25 +0x55
github.com/zenazn/goji/web.(*router).route(0xc2080103b8, 0xc208bd33b0, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/zenazn/goji/web/router.go:119 +0x144
github.com/zenazn/goji/web.func·002(0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/zenazn/goji/web/middleware.go:88 +0x60
net/http.HandlerFunc.ServeHTTP(0xc208e512e0, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·006(0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/drone/drone/server/middleware/user.go:21 +0x1b1
net/http.HandlerFunc.ServeHTTP(0xc208e513c0, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·001(0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/drone/drone/server/middleware/header.go:28 +0x4cc
net/http.HandlerFunc.ServeHTTP(0xc2092ee250, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /usr/src/go/src/net/http/server.go:1265 +0x41
main.func·002(0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/drone/drone/server/main.go:176 +0x885
net/http.HandlerFunc.ServeHTTP(0xc208e51480, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·002(0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/drone/drone/server/middleware/options.go:22 +0x256
net/http.HandlerFunc.ServeHTTP(0xc2092ee280, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/zenazn/goji/web.(*cStack).ServeHTTP(0xc208bd33b0, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/zenazn/goji/web/middleware.go:46 +0x72
github.com/zenazn/goji/web.(*Mux).ServeHTTP(0xc208010380, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /go/src/github.com/zenazn/goji/web/mux.go:45 +0x60
net/http.(*ServeMux).ServeHTTP(0xc20803a990, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20802f8c0, 0x7f7cafbdcf80, 0xc208d801e0, 0xc20931a000)
        /usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20899aa00)
        /usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/src/go/src/net/http/server.go:1751 +0x35e
```

**Comment by talexand** [comment]
Same issue here. I'll add more info when I find a hook that *doesn't* cause a panic.

**Comment by potz** [comment]
I'm also having these panics when first adding a repo to drone, on the "this will be your commit stream"  page. Running drone.io in a docker container with another container serving as an nginx reverse proxy.

**Comment by chuckbutler** [comment]
This appears fixed with the latest build from the .deb  0.3.0-alpha-1442513246
