### ISSUE TITLE
Bug: Cannot delete repo through the API

### ISSUE THREAD

**Issue by MichielDeMey** [drone/drone#1198]
I can GET the repo using the API request and it seems to work fine.
However, using the DELETE method it outputs the following stack trace:

```
2015/09/13 16:26:22 http: panic serving 80.200.141.199:53109: runtime error: invalid memory address or nil pointer dereference
goroutine 653 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/drone/drone/plugin/remote/github.DeleteKey(0xc208630a50, 0xc208357898, 0x7, 0xc2083578e0, 0xa, 0xc208309a60, 0x16, 0xc208126900, 0x17d, 0x0, ...)
	/gopath/src/github.com/drone/drone/plugin/remote/github/helper.go:250 +0xfa
github.com/drone/drone/plugin/remote/github.(*GitHub).Deactivate(0xc2080101c0, 0xc208630840, 0xc208196500, 0xc2085c0960, 0x55, 0x0, 0x0)
	/gopath/src/github.com/drone/drone/plugin/remote/github/github.go:207 +0x15f
github.com/drone/drone/server/handler.DelRepo(0xc2086c70e0, 0xc2086c6f00, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/handler/repo.go:78 +0x8a5
github.com/zenazn/goji/web.handlerFuncWrap.ServeHTTPC(0xd81c90, 0xc2086c70e0, 0xc2086c6f00, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/handler.go:25 +0x55
github.com/zenazn/goji/web.(*router).route(0xc208010ab8, 0xc2086c7110, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/router.go:119 +0x144
github.com/zenazn/goji/web.func·002(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/middleware.go:88 +0x60
net/http.HandlerFunc.ServeHTTP(0xc208309600, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·005(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/middleware/repo.go:104 +0x441
net/http.HandlerFunc.ServeHTTP(0xc208309620, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·004(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/middleware/repo.go:62 +0x21c
net/http.HandlerFunc.ServeHTTP(0xc208309660, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·003(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/middleware/repo.go:36 +0x5ec
net/http.HandlerFunc.ServeHTTP(0xc208309680, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/zenazn/goji/web.(*cStack).ServeHTTPC(0xc2086c7110, 0xc2086c70e0, 0xc2086c6f00, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/middleware.go:50 +0x91
github.com/zenazn/goji/web.(*Mux).ServeHTTPC(0xc208010a80, 0xc2086c70e0, 0xc2086c6f00, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/mux.go:53 +0x74
github.com/zenazn/goji/web.(*router).route(0xc2080103b8, 0xc2086c6ed0, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/router.go:119 +0x144
github.com/zenazn/goji/web.func·002(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/middleware.go:88 +0x60
net/http.HandlerFunc.ServeHTTP(0xc2083090a0, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·006(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/middleware/user.go:21 +0x1b1
net/http.HandlerFunc.ServeHTTP(0xc2083090e0, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·001(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/middleware/header.go:28 +0x4cc
net/http.HandlerFunc.ServeHTTP(0xc208356800, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
main.func·002(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/main.go:176 +0x885
net/http.HandlerFunc.ServeHTTP(0xc208309120, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/drone/drone/server/middleware.func·002(0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/drone/drone/server/middleware/options.go:22 +0x256
net/http.HandlerFunc.ServeHTTP(0xc208356830, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/zenazn/goji/web.(*cStack).ServeHTTP(0xc2086c6ed0, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/middleware.go:46 +0x72
github.com/zenazn/goji/web.(*Mux).ServeHTTP(0xc208010380, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/gopath/src/github.com/zenazn/goji/web/mux.go:45 +0x60
net/http.(*ServeMux).ServeHTTP(0xc20803a960, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc20802f5c0, 0x7fdffec4afe8, 0xc208376960, 0xc20861eea0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208058e60)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by bradrydzewski** [comment]
hmmm, it looks like it is having issues with the below line of code (in red). The GitHub API returning a nil value `*k.ID` (the key id) which is causing a panic. Any chance you can get a sample payload of the keys that I can use for troubleshooting? You'd have to manually invoke this:
https://developer.github.com/v3/repos/keys/#list

```diff
func DeleteKey(client *github.Client, owner, name, title, key string) error {
	var k, err = GetKey(client, owner, name, title)
	if err != nil {
		return err
	}
-	_, err = client.Repositories.DeleteKey(owner, name, *k.ID)
	return err
}
```

from https://github.com/drone/drone/blob/master/plugin/remote/github/helper.go#L250

**Comment by MichielDeMey** [comment]
I'm using the following curl request:
```
curl -I -X DELETE https://domain.com/api/repos/github.com/astromo/astromo.io?access_token=***
```

Maybe it cannot properly handle the '.' in the repo name?

I'll see if I can get you that list of keys from the Github API.

**Comment by bradrydzewski** [comment]
just tested delete. fixed in latest

```
[GIN] 200 | 14.472046ms | 127.0.0.1:43747 |   DELETE  /api/repos/bradrydzewski/ami-utils
[GIN] 200 |  1.635159ms | 127.0.0.1:43747 |   GET     /
```
