### ISSUE TITLE
Crashes when using postgres + gogs

### ISSUE THREAD

**Issue by sokoow** [drone/drone#1759]
Thank you for taking the time to use Drone and file an issue or feature request. Before filing an issue please ensure the following boxes are checked, if applicable:

- [X ] I have provided details from the server logs by running `docker logs drone`

I'm using 0.5.0 head build and when I'm logging in, I'm getting following stack. It happens every time after /authorize is called.

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x62 pc=0x7fb0279334]

runtime stack:
runtime.throw(0xe943a0, 0x2a)
	/usr/lib/go-1.6/src/runtime/panic.go:547 +0x80
runtime.sigpanic()
	/usr/lib/go-1.6/src/runtime/sigpanic_unix.go:12 +0x50

goroutine 13 [syscall, locked to thread]:
runtime.cgocall(0xa03728, 0x482003abc8, 0x0)
	/usr/lib/go-1.6/src/runtime/cgocall.go:123 +0x150 fp=0x482003ab60 sp=0x482003ab30
net._C2func_getaddrinfo(0x7fa00008c0, 0x0, 0x482042e0f0, 0x48200284b0, 0x0, 0x0, 0x0)
	??:0 +0x50 fp=0x482003abc0 sp=0x482003ab60
net.cgoLookupIPCNAME(0x482000baa0, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf0ac00)
	/usr/lib/go-1.6/src/net/cgo_unix.go:111 +0x390 fp=0x482003ad40 sp=0x482003abc0
net.cgoLookupIP(0x482000baa0, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4820028490)
	/usr/lib/go-1.6/src/net/cgo_unix.go:163 +0x4c fp=0x482003ada0 sp=0x482003ad40
net.lookupIP(0x482000baa0, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/lookup_unix.go:67 +0x68 fp=0x482003ae10 sp=0x482003ada0
net.glob.func16(0xf0ac90, 0x482000baa0, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/hook.go:10 +0x44 fp=0x482003ae50 sp=0x482003ae10
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/lookup.go:106 +0x60 fp=0x482003aed0 sp=0x482003ae50
internal/singleflight.(*Group).doCall(0x1275c70, 0x4820012500, 0x482000baa0, 0x12, 0x482000bb20)
	/usr/lib/go-1.6/src/internal/singleflight/singleflight.go:93 +0x20 fp=0x482003af80 sp=0x482003aed0
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_arm64.s:975 +0x4 fp=0x482003af80 sp=0x482003af80
created by internal/singleflight.(*Group).DoChan
	/usr/lib/go-1.6/src/internal/singleflight/singleflight.go:86 +0x380

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fb041d2c0, 0x72, 0x8)
	/usr/lib/go-1.6/src/runtime/netpoll.go:160 +0x78
net.(*pollDesc).Wait(0x48203a1720, 0x72, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x48203a1720, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).accept(0x48203a16c0, 0x0, 0x7fb144f208, 0x482000b500)
	/usr/lib/go-1.6/src/net/fd_unix.go:426 +0x244
net.(*TCPListener).AcceptTCP(0x4820028450, 0x482012cf18, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/tcpsock_posix.go:254 +0x4c
net/http.tcpKeepAliveListener.Accept(0x4820028450, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/server.go:2427 +0x30
net/http.(*Server).Serve(0x482039cf00, 0x7fb144f1d0, 0x4820028450, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/server.go:2117 +0x100
net/http.(*Server).ListenAndServe(0x482039cf00, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/server.go:2098 +0x134
net/http.ListenAndServe(0x482000f620, 0x5, 0x7fb144f170, 0x482008cd20, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/server.go:2195 +0x94
main.server(0x48201bf9e0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/drone/server.go:314 +0x438
main.glob.func24(0x48201bf9e0)
	/opt/go/src/github.com/drone/drone/drone/server.go:19 +0x20
github.com/drone/drone/vendor/github.com/codegangsta/cli.Command.Run(0xd967d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe4eb80, 0x1e, 0x0, ...)
	/opt/go/src/github.com/drone/drone/vendor/github.com/codegangsta/cli/command.go:131 +0xd7c
github.com/drone/drone/vendor/github.com/codegangsta/cli.(*App).Run(0x48201bf7a0, 0x4820090060, 0x2, 0x2, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/vendor/github.com/codegangsta/cli/app.go:175 +0xe24
main.main()
	/opt/go/src/github.com/drone/drone/drone/main.go:48 +0x4e4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_arm64.s:975 +0x4

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.6/src/runtime/sigqueue.go:116 +0x24c
os/signal.loop()
	/usr/lib/go-1.6/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go-1.6/src/os/signal/signal_unix.go:28 +0x3c

goroutine 21 [chan receive]:
database/sql.(*DB).connectionOpener(0x48200cb130)
	/usr/lib/go-1.6/src/database/sql/sql.go:727 +0x40
created by database/sql.Open
	/usr/lib/go-1.6/src/database/sql/sql.go:493 +0x2c8

goroutine 5 [select]:
net/http.(*persistConn).roundTrip(0x482039e680, 0x48203e3740, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:1473 +0xcf4
net/http.(*Transport).RoundTrip(0x482016e000, 0x48203f8540, 0x482016e000, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:324 +0x850
net/http.send(0x48203f8540, 0x7fb0417850, 0x482016e000, 0x0, 0x0, 0x0, 0x482038fc50, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:260 +0x5f8
net/http.(*Client).send(0x482038fb90, 0x48203f8540, 0x0, 0x0, 0x0, 0x481ffe0c91, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:155 +0x118
net/http.(*Client).doFollowingRedirects(0x482038fb90, 0x48203f8540, 0xf0aec8, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:475 +0x73c
net/http.(*Client).Do(0x482038fb90, 0x48203f8540, 0x4820128bf0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:188 +0xd8
github.com/drone/drone/vendor/github.com/gogits/go-gogs-client.(*Client).getResponse(0x4820128f18, 0xd8ec78, 0x3, 0xd9c810, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gogits/go-gogs-client/gogs.go:51 +0x2bc
github.com/drone/drone/vendor/github.com/gogits/go-gogs-client.(*Client).getParsedResponse(0x4820128f18, 0xd8ec78, 0x3, 0xd9c810, 0xb, 0x0, 0x0, 0x0, 0xb1d1c0, 0x482038b6a0, ...)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gogits/go-gogs-client/gogs.go:81 +0x60
github.com/drone/drone/vendor/github.com/gogits/go-gogs-client.(*Client).ListMyRepos(0x4820128f18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gogits/go-gogs-client/repo.go:37 +0xfc
github.com/drone/drone/remote/gogs.(*client).Repos(0x482022e3c0, 0x48203e9000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/remote/gogs/gogs.go:145 +0x370
github.com/drone/drone/remote.Repos(0x7fb144f4f0, 0x48203c6630, 0x48203e9000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/remote/remote.go:90 +0x60
github.com/drone/drone/cache.GetRepos(0x7fb144f4f0, 0x48203c6630, 0x48203e9000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/cache/helper.go:47 +0x1ac
github.com/drone/drone/server.GetFeed(0x48203c6630)
	/opt/go/src/github.com/drone/drone/server/user.go:26 +0x194
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/session.MustUser.func1(0x48203c6630)
	/opt/go/src/github.com/drone/drone/router/middleware/session/user.go:113 +0x134
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/token.Refresh(0x48203c6630)
	/opt/go/src/github.com/drone/drone/router/middleware/token/token.go:26 +0x1ec
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/session.SetUser.func1(0x48203c6630)
	/opt/go/src/github.com/drone/drone/router/middleware/session/user.go:68 +0x368
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware.Store.func1(0x48203c6630)
	/opt/go/src/github.com/drone/drone/router/middleware/store.go:17 +0xa8
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/vendor/github.com/gin-gonic/contrib/ginrus.Ginrus.func1(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/contrib/ginrus/ginrus.go:26 +0x84
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/header.Options(0x48203c6630)
	/opt/go/src/github.com/drone/drone/router/middleware/header/header.go:25 +0x190
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/header.NoCache(0x48203c6630)
	/opt/go/src/github.com/drone/drone/router/middleware/header/header.go:17 +0x128
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/vendor/github.com/gin-gonic/gin.RecoveryWithWriter.func1(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/recovery.go:45 +0x64
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x482008cd20, 0x48203c6630)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:284 +0x220
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x482008cd20, 0x7fb144f300, 0x48203f68f0, 0x48203f8460)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:265 +0x1b8
net/http.serverHandler.ServeHTTP(0x482039cf00, 0x7fb144f300, 0x48203f68f0, 0x48203f8460)
	/usr/lib/go-1.6/src/net/http/server.go:2081 +0x1a8
net/http.(*conn).serve(0x482039cf80)
	/usr/lib/go-1.6/src/net/http/server.go:1472 +0xee8
created by net/http.(*Server).Serve
	/usr/lib/go-1.6/src/net/http/server.go:2137 +0x3a4

goroutine 11 [select]:
net/http.(*Transport).getConn(0x482016e000, 0x482000c700, 0x0, 0x4820015f80, 0x4, 0x482000baa0, 0x15, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:711 +0x3ec
net/http.(*Transport).RoundTrip(0x482016e000, 0x482000c700, 0x482016e000, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:311 +0x6e4
net/http.send(0x482000c700, 0x7fb0417850, 0x482016e000, 0x0, 0x0, 0x0, 0x482042e030, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:260 +0x5f8
net/http.(*Client).send(0x4820015f50, 0x482000c700, 0x0, 0x0, 0x0, 0x481ffe17a7, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:155 +0x118
net/http.(*Client).doFollowingRedirects(0x4820015f50, 0x482000c700, 0xf0aec8, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:475 +0x73c
net/http.(*Client).Do(0x4820015f50, 0x482000c700, 0x4820426c40, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/client.go:188 +0xd8
github.com/drone/drone/vendor/github.com/gogits/go-gogs-client.(*Client).getResponse(0x4820426f68, 0xd8ec78, 0x3, 0xd9c810, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gogits/go-gogs-client/gogs.go:51 +0x2bc
github.com/drone/drone/vendor/github.com/gogits/go-gogs-client.(*Client).getParsedResponse(0x4820426f68, 0xd8ec78, 0x3, 0xd9c810, 0xb, 0x0, 0x0, 0x0, 0xb1d1c0, 0x482000ba80, ...)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gogits/go-gogs-client/gogs.go:81 +0x60
github.com/drone/drone/vendor/github.com/gogits/go-gogs-client.(*Client).ListMyRepos(0x4820426f68, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gogits/go-gogs-client/repo.go:37 +0xfc
github.com/drone/drone/remote/gogs.(*client).Repos(0x482022e3c0, 0x482039d400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/remote/gogs/gogs.go:145 +0x370
github.com/drone/drone/remote.Repos(0x7fb144f4f0, 0x48203c6840, 0x482039d400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/remote/remote.go:90 +0x60
github.com/drone/drone/cache.GetRepos(0x7fb144f4f0, 0x48203c6840, 0x482039d400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/cache/helper.go:47 +0x1ac
github.com/drone/drone/cache.GetRepoMap(0x7fb144f4f0, 0x48203c6840, 0x482039d400, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/drone/drone/cache/helper.go:59 +0x3c
github.com/drone/drone/server.EventStream(0x48203c6840)
	/opt/go/src/github.com/drone/drone/server/stream.go:227 +0x368
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/token.Refresh(0x48203c6840)
	/opt/go/src/github.com/drone/drone/router/middleware/token/token.go:26 +0x1ec
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/session.SetUser.func1(0x48203c6840)
	/opt/go/src/github.com/drone/drone/router/middleware/session/user.go:68 +0x368
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware.Store.func1(0x48203c6840)
	/opt/go/src/github.com/drone/drone/router/middleware/store.go:17 +0xa8
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/vendor/github.com/gin-gonic/contrib/ginrus.Ginrus.func1(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/contrib/ginrus/ginrus.go:26 +0x84
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/header.Options(0x48203c6840)
	/opt/go/src/github.com/drone/drone/router/middleware/header/header.go:25 +0x190
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/router/middleware/header.NoCache(0x48203c6840)
	/opt/go/src/github.com/drone/drone/router/middleware/header/header.go:17 +0x128
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/vendor/github.com/gin-gonic/gin.RecoveryWithWriter.func1(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/recovery.go:45 +0x64
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Context).Next(0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:97 +0xa4
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x482008cd20, 0x48203c6840)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:284 +0x220
github.com/drone/drone/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x482008cd20, 0x7fb144f300, 0x482039e820, 0x482000c540)
	/opt/go/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:265 +0x1b8
net/http.serverHandler.ServeHTTP(0x482039cf00, 0x7fb144f300, 0x482039e820, 0x482000c540)
	/usr/lib/go-1.6/src/net/http/server.go:2081 +0x1a8
net/http.(*conn).serve(0x482039d300)
	/usr/lib/go-1.6/src/net/http/server.go:1472 +0xee8
created by net/http.(*Server).Serve
	/usr/lib/go-1.6/src/net/http/server.go:2137 +0x3a4

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7fb041d140, 0x72, 0x8)
	/usr/lib/go-1.6/src/runtime/netpoll.go:160 +0x78
net.(*pollDesc).Wait(0x48203a1950, 0x72, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x48203a1950, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x48203a18f0, 0x48203d6000, 0x1000, 0x1000, 0x0, 0x7fb040f028, 0x482006e0b0)
	/usr/lib/go-1.6/src/net/fd_unix.go:250 +0x1d0
net.(*conn).Read(0x4820028480, 0x48203d6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/net.go:172 +0xe8
net/http.noteEOFReader.Read(0x7fb041d440, 0x4820028480, 0x482039e6e8, 0x48203d6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:1687 +0x58
net/http.(*noteEOFReader).Read(0x482000b3c0, 0x48203d6000, 0x1000, 0x1000, 0x15, 0x0, 0x0)
	<autogenerated>:284 +0xf0
bufio.(*Reader).fill(0x48203c9740)
	/usr/lib/go-1.6/src/bufio/bufio.go:97 +0x1c0
bufio.(*Reader).Peek(0x48203c9740, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/bufio/bufio.go:132 +0xd4
net/http.(*persistConn).readLoop(0x482039e680)
	/usr/lib/go-1.6/src/net/http/transport.go:1073 +0x194
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.6/src/net/http/transport.go:857 +0xf10

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0x482039e680)
	/usr/lib/go-1.6/src/net/http/transport.go:1277 +0x368
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.6/src/net/http/transport.go:858 +0xf30

goroutine 12 [select]:
net.lookupIPDeadline(0x482000baa0, 0x12, 0xecf4163ff, 0x358395c0, 0x1276de0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/lookup.go:109 +0x518
net.internetAddrList(0xd970e0, 0x3, 0x482000baa0, 0x15, 0xecf4163ff, 0x358395c0, 0x1276de0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.6/src/net/ipsock.go:252 +0x510
net.resolveAddrList(0xd92a28, 0x4, 0xd970e0, 0x3, 0x482000baa0, 0x15, 0xecf4163ff, 0x48358395c0, 0x1276de0, 0x0, ...)
	/usr/lib/go-1.6/src/net/dial.go:158 +0x338
net.(*Dialer).Dial(0x4820092be0, 0xd970e0, 0x3, 0x482000baa0, 0x15, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/dial.go:216 +0xec
net.(*Dialer).Dial-fm(0xd970e0, 0x3, 0x482000baa0, 0x15, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:38 +0x50
net/http.(*Transport).dial(0x482016e000, 0xd970e0, 0x3, 0x482000baa0, 0x15, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:659 +0x64
net/http.(*Transport).dialConn(0x482016e000, 0x0, 0x4820015f80, 0x4, 0x482000baa0, 0x15, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/net/http/transport.go:762 +0x19b4
net/http.(*Transport).getConn.func4(0x482016e000, 0x0, 0x4820015f80, 0x4, 0x482000baa0, 0x15, 0x48203c9b60)
	/usr/lib/go-1.6/src/net/http/transport.go:706 +0x48
created by net/http.(*Transport).getConn
	/usr/lib/go-1.6/src/net/http/transport.go:708 +0x1e4
```

**Comment by bradrydzewski** [comment]
I cannot repeat running latest drone and my gogs install. I also see all the panics coming from the vendored gogs library at https://github.com/gogits/go-gogs-client/blob/master/gogs.go#L51

**Comment by bradrydzewski** [comment]
are you sure there isn't a low-level issue w/ networking on your machine that is causing a failure? The panic seems to be coming from the sdk in the Go client, so it is not clear to me that this is a drone issue.

I also see this is running on arm .... /usr/lib/go-1.6/src/runtime/asm_arm64.s:975 +0x4

I'm willing to accept pull requests if you find an issue with drone, but from what I can tell these panics are coming from the Go standard library, in the networking stack.

**Comment by sokoow** [comment]
it actually looks like glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=20468

**Comment by sokoow** [comment]
this is https://github.com/golang/go/issues/13470
