### ISSUE TITLE
Server Panic

### ISSUE THREAD

**Issue by guiguan** [drone/drone#1903]
We always get this error when we are using drone:latest (0.5):

```
1:M 18 Jan 06:19:09.364 * stomp: unsubscribe 1: successful: destination /topic/cancel
1:M 18 Jan 06:19:11.287 * stomp: unsubscribe 11: successful: destination /topic/logs.21
1:M 18 Jan 06:19:11.287 * stomp client: subscription not found: 11
1:M 18 Jan 06:21:17.160 * stomp: unsubscribe 2: successful: destination /topic/cancel
1:M 18 Jan 06:21:20.011 * stomp: unsubscribe 12: successful: destination /topic/logs.22
1:M 18 Jan 06:21:20.011 * stomp client: subscription not found: 12
1:M 18 Jan 06:35:15.058 * stomp: unsubscribe 4: successful: destination /topic/cancel
1:M 18 Jan 06:35:15.058 * stomp: unsubscribe 14: successful: destination /topic/logs.22
1:M 18 Jan 06:35:17.343 * stomp: unsubscribe 15: successful: destination /topic/logs.22
1:M 18 Jan 06:35:17.343 * stomp client: subscription not found: 15
1:M 18 Jan 06:38:07.271 * stomp: unsubscribe 3: successful: destination /topic/cancel
1:M 18 Jan 06:38:08.956 * stomp: unsubscribe 16: successful: destination /topic/logs.23
1:M 18 Jan 06:38:08.956 * stomp client: subscription not found: 16
1:M 18 Jan 06:41:28.819 * stomp: unsubscribe 13: successful: destination /topic/events
1:M 18 Jan 17:10:17.403 * stomp: unsubscribe 17: successful: destination /topic/events
1:M 18 Jan 21:53:41.978 * stomp: unsubscribe 18: successful: destination /topic/events
1:M 19 Jan 01:55:23.177 * stomp: ack 1577364546661025983: message not found
1:M 19 Jan 01:55:23.177 # stomp: server panic: runtime error: invalid memory address or nil pointer dereference
1:M 19 Jan 01:56:26.214 * stomp: unsubscribe 19: successful: destination /topic/events
```

Then, all our pipelines stopped, and we have to restart our drone server container to make them continue.

**Comment by bradrydzewski** [comment]
This is not an error message, this is a debug message indicating a listener (which could be a web browser) successfully unsubscribed from the event queue. It is also not a panic, as mentioned in the title. If there was a panic, we should see a stacktrace and it should be included in this issue.

In order to help we would need more information.

**Comment by guiguan** [comment]
@bradrydzewski ops, sorry. I pasted the wrong error msg. Should be this one:

```
1:M 19 Jan 01:55:23.177 # stomp: server panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by bradrydzewski** [comment]
is there any more to that error?

**Comment by guiguan** [comment]
@bradrydzewski Have a look of the updated msg

**Comment by guiguan** [comment]
@bradrydzewski Those are from drone agent:

```
1:M 19 Jan 01:41:32.783 # Error updating XXXX/XXX-XX#20.1. EOF
1:M 19 Jan 01:41:32.783 # Error sending eof  XXXX/XXX-XX#20.1. EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x70f682]

goroutine 4456 [running]:
panic(0xd84960, 0xc8200100a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/drone/mq/stomp.(*Client).sendMessage(0x0, 0xc820587a00, 0x0, 0x0)
	/go/src/github.com/drone/mq/stomp/client.go:232 +0xa2
github.com/drone/mq/stomp.(*Client).Ack(0x0, 0xc82057b055, 0x13, 0xd77, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/drone/mq/stomp/client.go:119 +0xc1
github.com/drone/drone/drone/agent.start.func1.1(0xc8200261c8, 0xc82015e000)
	/go/src/github.com/drone/drone/drone/agent/agent.go:187 +0x72
github.com/drone/drone/drone/agent.start.func1(0xc82015e000)
	/go/src/github.com/drone/drone/drone/agent/agent.go:207 +0x682
created by github.com/drone/drone/drone/agent.start.func2
	/go/src/github.com/drone/drone/drone/agent/agent.go:244 +0x32
1:M 19 Jan 01:51:07.175 * connecting to server wss://drone.XXXX.com/ws/broker
1:M 19 Jan 01:51:07.563 * connection established, ready to process builds.
1:M 19 Jan 01:51:37.368 - stomp: send heart-beat.
1:M 19 Jan 01:51:37.464 - stomp: received heart-beat
1:M 19 Jan 01:52:07.367 - stomp: send heart-beat.
```

**Comment by guiguan** [comment]
@bradrydzewski I think it is caused by a connection lost

**Comment by guiguan** [comment]
@bradrydzewski it seems to happen whenever there is an `ack *: message not found`

**Comment by guiguan** [comment]
@bradrydzewski any progress on this issue? :)

**Comment by gtaylor** [comment]
@guiguan He'll post here when there is.

**Comment by bradrydzewski** [comment]
removed stomp from latest version, thus removing the panic

**Comment by guiguan** [comment]
Nice
