### ISSUE TITLE
nil pointer dereference on linter

### ISSUE THREAD

**Issue by domgoer** [drone/drone#2869]
**log**

```bash
{"arch":"amd64","build":46,"level":"error","machine":"ip-192-168-123-142.ap-northeast-1.compute.internal","msg":"runner: unexpected panic: runtime error: invalid memory address or nil pointer dereference","os":"linux","pipeline":"api-gateway-k8s","repo":"iftechio/api-gateway-k8s","stage":1,"stage-id":6438,"time":"2019-11-05T09:15:03Z"}
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0x1, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/drone/drone/operator/runner.(*Runner).Run.func1(0xc0006d67a0)
	/drone/src/operator/runner/runner.go:134 +0xa1
panic(0x11e3740, 0x1da0110)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/drone/drone-yaml/yaml/linter.checkPipeline(0xc0004bea80, 0x0, 0x0, 0xc0008cd9c0)
	/go/pkg/mod/github.com/drone/drone-yaml@v1.2.3-0.20190902155851-ad8ad9816fbf/yaml/linter/linter.go:80 +0x1ac
github.com/drone/drone-yaml/yaml/linter.Lint(0x1521dc0, 0xc0004bea80, 0xc00040e400, 0x8, 0xc0006d7260)
	/go/pkg/mod/github.com/drone/drone-yaml@v1.2.3-0.20190902155851-ad8ad9816fbf/yaml/linter/linter.go:54 +0x337
github.com/drone/drone/operator/runner.(*Runner).Run(0xc0004b4600, 0x154ec40, 0xc00030ba80, 0x1926, 0x0, 0x0)
	/drone/src/operator/runner/runner.go:234 +0x185a
main.main()
```

**recurrent**

When using starlark, during the step creation phase, a function returns null incorrectly.

```py
def make_pipeline(ctx):
    return {
        'kind': 'pipeline',
        'name': 'xxx',
        'steps': [
            get_null(),
            ...
        ]
    }
```

In the web page, the build has been in the Pending state, so I looked at the log and found this problem.

fix in [drone-yaml#55](https://github.com/drone/drone-yaml/pull/55)

**Comment by bradrydzewski** [comment]
:wave: hey there, thanks for the pull request

the code for the agent has been moved here:
https://github.com/drone-runners/drone-runner-docker

the new code has a check for nil steps to prevent this scenario:
https://github.com/drone-runners/drone-runner-docker/blob/master/engine/resource/parser.go#L43:L44

the new agent is also distributed using a new docker image, see:
https://docker-runner.docs.drone.io/installation/install_linux/
