### ISSUE TITLE
Document MySQL database creation

### ISSUE THREAD

**Issue by davidak** [drone/drone#917]
i setup a server like described, but drone don't create the database itself.

http://readme.drone.io/setup/database/mysql/

```
panic: Could not get DB version: Error 1049: Unknown database 'drone'

goroutine 16 [running]:
runtime.panic(0xab3d40, 0xc2081371b0)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/drone/drone/server/datastore/database.MustConnect(0xc208136e10, 0x5, 0xc20811ed80, 0x1e, 0x0)
        /var/cache/drone/src/github.com/drone/drone/server/datastore/database/database.go:52 +0x8a
main.main()
        /var/cache/drone/src/github.com/drone/drone/server/main.go:104 +0x274

goroutine 19 [finalizer wait]:
runtime.park(0x4a8570, 0x11caf90, 0x11b59e9)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x11caf90, 0x11b59e9)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 22 [syscall]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 24 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208050380)
        /usr/local/go/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
        /usr/local/go/src/pkg/database/sql/sql.go:442 +0x27c
```

**Comment by davidak** [comment]
workaround: `mysql> create database drone;`
