### ISSUE TITLE
drone start before mysql

### ISSUE THREAD

**Issue by davidak** [drone/drone#919]
i have drone configured with mysql.

maybe upstart starts drone before mysql.

the upstart scripts needs to wait for mysql BUT ONLY if it's used.

it works with `service drone start` after the server started.

```
panic: Could not get DB version: dial tcp 127.0.0.1:3306: connection refused

goroutine 16 [running]:
runtime.panic(0xab3d40, 0xc2081275e0)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/drone/drone/server/datastore/database.MustConnect(0xc2081272c0, 0x5, 0xc2081284e0, 0x1e, 0x0)
        /var/cache/drone/src/github.com/drone/drone/server/datastore/database/database.go:52 +0x8a
main.main()
        /var/cache/drone/src/github.com/drone/drone/server/main.go:104 +0x274

goroutine 19 [finalizer wait]:
runtime.park(0x4a8570, 0x11caf90, 0x11b59e9)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x11caf90, 0x11b59e9)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 22 [syscall]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 24 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208060480)
        /usr/local/go/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
        /usr/local/go/src/pkg/database/sql/sql.go:442 +0x27c
starting build
2015/03/16 18:08:55 x509: certificate is valid for grml, not localhost
2015/03/16 18:08:56 subscription's close channel received message
panic: Could not get DB version: dial tcp 127.0.0.1:3306: connection refused

goroutine 16 [running]:
runtime.panic(0xab3d40, 0xc208127540)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/drone/drone/server/datastore/database.MustConnect(0xc208127220, 0x5, 0xc208128400, 0x1e, 0x0)
        /var/cache/drone/src/github.com/drone/drone/server/datastore/database/database.go:52 +0x8a
main.main()
        /var/cache/drone/src/github.com/drone/drone/server/main.go:104 +0x274

goroutine 19 [finalizer wait]:
runtime.park(0x4a8570, 0x11caf90, 0x11b59e9)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x11caf90, 0x11b59e9)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 22 [syscall]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 24 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208060480)
        /usr/local/go/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
        /usr/local/go/src/pkg/database/sql/sql.go:442 +0x27c
```

**Comment by bradrydzewski** [comment]
Good to know, thanks. Maybe we can do a backoff when trying to connect.

Also, just a heads up, there are some known issues with the Go mysql driver that will cause the connection to timeout, and then the next immediate request to hang for 15 minutes:
https://github.com/go-sql-driver/mysql/issues/257

**Comment by bradrydzewski** [comment]
fixed in latest build
