### ISSUE TITLE
nil pointer dereference on Rebuild

### ISSUE THREAD

**Issue by jpillora** [drone/drone#982]
Im running [Drone in a container](https://www.digitalocean.com/community/tutorials/how-to-perform-continuous-integration-testing-with-drone-io-on-coreos-and-docker) and I was having network issues so I was adding and removing the drone server. Got this after I clicked "Rebuild".

```
2015/04/18 09:37:27 http: panic serving 172.17.8.1:53133: runtime error: invalid memory address or nil pointer dereference
goroutine 31 [running]:
net/http.func·011()
	/usr/local/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0xb3afc0, 0x11ad913)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/drone/drone/server/handler.PostCommit(0xc2081815f0, 0xc2081812f0, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/handler/commit.go:104 +0x5e3
github.com/zenazn/goji/web.handlerFuncWrap.ServeHTTPC(0xd52dd0, 0xc2081815f0, 0xc2081812f0, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/handler.go:25 +0x54
github.com/zenazn/goji/web.(*router).route(0xc208028b28, 0xc2081dc630, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/router.go:119 +0x143
github.com/zenazn/goji/web.func·002(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/middleware.go:88 +0x5f
net/http.HandlerFunc.ServeHTTP(0xc2081c7900, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/drone/drone/server/middleware.func·005(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/middleware/repo.go:104 +0x45b
net/http.HandlerFunc.ServeHTTP(0xc2081c7920, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/drone/drone/server/middleware.func·004(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/middleware/repo.go:62 +0x21d
net/http.HandlerFunc.ServeHTTP(0xc2081c7940, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/drone/drone/server/middleware.func·003(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/middleware/repo.go:36 +0x5dc
net/http.HandlerFunc.ServeHTTP(0xc2081c7960, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/zenazn/goji/web.(*cStack).ServeHTTPC(0xc2081dc630, 0xc2081815f0, 0xc2081812f0, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/middleware.go:50 +0x69
github.com/zenazn/goji/web.(*Mux).ServeHTTPC(0xc208028af0, 0xc2081815f0, 0xc2081812f0, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/mux.go:53 +0x73
github.com/zenazn/goji/web.(*router).route(0xc208028348, 0xc2081b76e0, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/router.go:119 +0x143
github.com/zenazn/goji/web.func·002(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/middleware.go:88 +0x5f
net/http.HandlerFunc.ServeHTTP(0xc2081c7c40, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/drone/drone/server/middleware.func·006(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/middleware/user.go:21 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc2081c7c60, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/drone/drone/server/middleware.func·001(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/middleware/header.go:28 +0x4e9
net/http.HandlerFunc.ServeHTTP(0xc208176860, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
main.func·002(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/main.go:176 +0x721
net/http.HandlerFunc.ServeHTTP(0xc2081c7c80, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/drone/drone/server/middleware.func·002(0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/drone/drone/server/middleware/options.go:22 +0x261
net/http.HandlerFunc.ServeHTTP(0xc208176890, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
github.com/zenazn/goji/web.(*cStack).ServeHTTP(0xc2081b76e0, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/middleware.go:46 +0x7f
github.com/zenazn/goji/web.(*Mux).ServeHTTP(0xc208028310, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/var/cache/drone/src/github.com/zenazn/goji/web/mux.go:45 +0x5f
net/http.(*ServeMux).ServeHTTP(0xc208022930, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080059e0, 0x7fabe81609f0, 0xc2081b9400, 0xc2081f4c30)
	/usr/local/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208051100)
	/usr/local/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
	/usr/local/go/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by bradrydzewski** [comment]
this would be the line of code referenced in the above stack trace:

```Go
// Request a new token and update
user_token, err := remote.GetToken(owner)
```

the `remote` represents the remote system that you configured to work with Drone (ie GitHub, Bitbucket, etc). Typically `remote` would only be nil if GitHub (or whatever) wasn't properly configured when Drone was started.  This is strange, however, because in order to receive a post-commit hook from GitHub you would have had to correctly setup GitHub, Login to Drone and activate a repository.

can you shed any more light on this? Is it possible you had a semi-working Drone configuration, activated a repository, but then change your remote configuration and put it in a non-working state, after which a post-commit hook was received?

**Comment by jpillora** [comment]
I'm running 1 Docker VM with Drone and Gitlab installed as containers (docker socket exposed). I think you're right, it was after a few wipes of the Drone container, while keeping the sqlite db in a Docker volume, so maybe the db was corrupted. Not sure, it's all fixed now so it's hard to reproduce, though thought I'd report incase it needed a fix – I'll close this for now, can be reopened if it causes someone issues. Awesome project btw – much simpler and better looking than Gitlab CI :+1:
